---
- hosts: localhost
  connection: local
  gather_facts: True
  become: True
  roles:
    - role: users
    - role: utc-timezone
    - role: sar
    - role: banner
    - role: openstackclient
    - role: iptables
    - { role: consul, clientServer: 'server' }
    - role: k8s-controller
